# Generated by Django 2.1.5 on 2019-01-24 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOARD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=20)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hit', models.IntegerField(default=0)),
            ],
        ),
    ]
