# Generated by Django 2.1.5 on 2019-01-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190130_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['-create_at']},
        ),
    ]
